export enum EnvironmentVariables {
    BASE_WELCOMEMESSAGEFORJOINROOM = 'BASE_WELCOMEMESSAGEFORJOINROOM',
    BASE_WELCOMEMESSAGEFORADDFRIEND = 'BASE_WELCOMEMESSAGEFORADDFRIEND',
    BASE_BOT_ID = 'BASE_BOT_ID',
    WECHATY_PUPPET = 'WECHATY_PUPPET',
    WECHATY_TOKEN = 'WECHATY_TOKEN',
    WXOPENAI_APPID = 'WXOPENAI_APPID',
    WXOPENAI_MANAGERID = 'WXOPENAI_MANAGERID',
    VIKA_SPACE_NAME = 'VIKA_SPACE_NAME',
    VIKA_TOKEN = 'VIKA_TOKEN',
    ADMINROOM_ADMINROOMID = 'ADMINROOM_ADMINROOMID',
    ADMINROOM_ADMINROOMTOPIC = 'ADMINROOM_ADMINROOMTOPIC',
    DATA_BASE_TYPE = 'DATA_BASE_TYPE',
    WXOPENAI_TOKEN = 'WXOPENAI_TOKEN',
    WXOPENAI_ENCODINGAESKEY = 'WXOPENAI_ENCODINGAESKEY',
    CHATGPT_KEY = 'CHATGPT_KEY',
    CHATGPT_ENDPOINT = 'CHATGPT_ENDPOINT',
    CHATGPT_MODEL='CHATGPT_MODEL',
    ERNIE_AK='ERNIE_AK',
    ERNIE_SK='ERNIE_SK',
    MQTT_USERNAME = 'MQTT_USERNAME',
    MQTT_PASSWORD = 'MQTT_PASSWORD',
    MQTT_ENDPOINT = 'MQTT_ENDPOINT',
    MQTT_PORT = 'MQTT_PORT',
    MQTT_PORT_SSL = 'MQTT_PORT_SSL',
    WEBHOOK_URL = 'WEBHOOK_URL',
    WEBHOOK_TOKEN = 'WEBHOOK_TOKEN',
    WEBHOOK_USERNAME = 'WEBHOOK_USERNAME',
    WEBHOOK_PASSWORD = 'WEBHOOK_PASSWORD',
    YUQUE_TOKEN = 'YUQUE_TOKEN',
    YUQUE_NAMESPACE = 'YUQUE_NAMESPACE',
    AUTOQA_AUTOREPLY = 'AUTOQA_AUTOREPLY',
    VIKA_USEVIKA = 'VIKA_USEVIKA',
    VIKA_UPLOADMESSAGETOVIKA = 'VIKA_UPLOADMESSAGETOVIKA',
    WEBHOOK_WEBHOOKMESSAGEPUSH = 'WEBHOOK_WEBHOOKMESSAGEPUSH',
    MQTT_MQTTMESSAGEPUSH = 'MQTT_MQTTMESSAGEPUSH',
    MQTT_MQTTCONTROL = 'MQTT_MQTTCONTROL',
    LARK_APP_ID='LARK_APP_ID',
    LARK_APP_SECRET='LARK_APP_SECRET',
    LARK_BITABLE_APP_TOKEN='LARK_BITABLE_APP_TOKEN',
    LARK_APP_USER_MOBILE='LARK_APP_USER_MOBILE',
    accessKeyId = 'accessKeyId',
    secretAccessKey = 'secretAccessKey',
    region = 'region',
    endpoint = 'endpoint',
    bucketName = 'bucketName',
  }

export interface ProcessEnv {
    // 维格表配置
    VIKA_SPACE_NAME: string;
    VIKA_TOKEN: string;

    // Wechaty配置
    WECHATY_PUPPET: string;
    WECHATY_TOKEN: string;

    // 基础配置
    ADMINROOM_ADMINROOMID: string;
    ADMINROOM_ADMINROOMTOPIC: string;
    BASE_BOT_ID: string;
    BASE_WELCOME_MESSAGE_FOR_ADD_FRIEND: string;
    DATA_BASE_TYPE?:'vika' | 'lark' | undefined ;

    // 飞书多维表格配置
    LARK_APP_ID: string;
    LARK_APP_SECRET: string;
    LARK_BITABLE_APP_TOKEN: string;
    LARK_APP_USER_MOBILE: string;

    // 智能问答配置
    WXOPENAI_TOKEN: string;
    WXOPENAI_ENCODINGAESKEY: string;
    WXOPENAI_APPID: string;
    WXOPENAI_MANAGERID: string;

    // ChatGPT
    CHATGPT_KEY: string;
    CHATGPT_ENDPOINT: string;
    CHATGPT_MODEL:string;

    // ERNIE
    ERNIE_AK:string;
    ERNIE_SK:string;

    // MQTT配置
    MQTT_USERNAME: string;
    MQTT_PASSWORD: string;
    MQTT_ENDPOINT: string;
    MQTT_PORT: string;
    MQTT_PORT_SSL: string;

    // 消息推送目的地配置
    WEBHOOK_URL: string;
    WEBHOOK_TOKEN: string;
    WEBHOOK_USERNAME: string;
    WEBHOOK_PASSWORD: string;

    // 语雀配置
    YUQUE_TOKEN: string;
    YUQUE_NAMESPACE: string;

    // 系统消息推送
    MESSAGE_ENCRYPT: string | boolean;
    MESSAGE_ENCODINGAESKEY: string;
    MESSAGE_WEB_HOOK: string;

    // 功能开关
    AUTOQA_AUTOREPLY: string | boolean;

    // 维格表配置
    VIKA_USEVIKA: string | boolean;
    VIKA_UPLOADMESSAGETOVIKA: string | boolean;

    WEBHOOK_WEBHOOKMESSAGEPUSH: string | boolean;

    MQTT_MQTTMESSAGEPUSH: string | boolean;
    MQTT_MQTTCONTROL: string | boolean;

    accessKeyId: string;
    secretAccessKey: string;
    region: string;
    endpoint: string;
    bucketName: string;
  }
